package javacore.distributed.javacore.websericve.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WarehouseService", targetNamespace = "http://websericve.javacore.distributed.javacore/", wsdlLocation = "http://localhost:8080/WebServices/warehouse?wsdl")
public class WarehouseService extends Service
{

    private final static URL                 WAREHOUSESERVICE_WSDL_LOCATION;

    private final static WebServiceException WAREHOUSESERVICE_EXCEPTION;

    private final static QName               WAREHOUSESERVICE_QNAME = new QName(
                                                                            "http://websericve.javacore.distributed.javacore/",
                                                                            "WarehouseService");

    static
    {
        URL url = null;
        WebServiceException e = null;
        try
        {
            url = new URL("http://localhost:8080/WebServices/warehouse?wsdl");
        }
        catch (MalformedURLException ex)
        {
            e = new WebServiceException(ex);
        }
        WAREHOUSESERVICE_WSDL_LOCATION = url;
        WAREHOUSESERVICE_EXCEPTION = e;
    }

    public WarehouseService()
    {
        super(__getWsdlLocation(), WAREHOUSESERVICE_QNAME);
    }

    // 1.7支持
    // public WarehouseService(WebServiceFeature... features) {
    // super(__getWsdlLocation(), WAREHOUSESERVICE_QNAME, features);
    // }

    public WarehouseService(URL wsdlLocation)
    {
        super(wsdlLocation, WAREHOUSESERVICE_QNAME);
    }

    // 1.7支持
    // public WarehouseService(URL wsdlLocation, WebServiceFeature... features) {
    // super(wsdlLocation, WAREHOUSESERVICE_QNAME, features);
    // }

    public WarehouseService(URL wsdlLocation, QName serviceName)
    {
        super(wsdlLocation, serviceName);
    }

    // 1.7支持
    // public WarehouseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    // super(wsdlLocation, serviceName, features);
    // }

    /**
     * 
     * @return
     *         returns Warehouse
     */
    @WebEndpoint(name = "WarehousePort")
    public Warehouse getWarehousePort()
    {
        return super.getPort(new QName("http://websericve.javacore.distributed.javacore/", "WarehousePort"),
                Warehouse.class);
    }

    /**
     * 
     * @param features
     *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
     *            the <code>features</code> parameter will have their default values.
     * @return
     *         returns Warehouse
     */
    @WebEndpoint(name = "WarehousePort")
    public Warehouse getWarehousePort(WebServiceFeature... features)
    {
        return super.getPort(new QName("http://websericve.javacore.distributed.javacore/", "WarehousePort"),
                Warehouse.class, features);
    }

    private static URL __getWsdlLocation()
    {
        if (WAREHOUSESERVICE_EXCEPTION != null)
        {
            throw WAREHOUSESERVICE_EXCEPTION;
        }
        return WAREHOUSESERVICE_WSDL_LOCATION;
    }

}
